package com.example.demo.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import lombok.Data;

@Data
public class Students {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.id
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.stu_name
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.gender
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.birthday
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    @DateTimeFormat(pattern = "yyyyMMdd")
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.phone
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.address
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.delflge
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    private Integer delflge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.create_date
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.update_date
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.delete_date
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    private Date deleteDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.id
     *
     * @return the value of students.id
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.id
     *
     * @param id the value for students.id
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.stu_name
     *
     * @return the value of students.stu_name
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.stu_name
     *
     * @param stuName the value for students.stu_name
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.gender
     *
     * @return the value of students.gender
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.gender
     *
     * @param gender the value for students.gender
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.birthday
     *
     * @return the value of students.birthday
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.birthday
     *
     * @param birthday the value for students.birthday
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.phone
     *
     * @return the value of students.phone
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.phone
     *
     * @param phone the value for students.phone
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.address
     *
     * @return the value of students.address
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.address
     *
     * @param address the value for students.address
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.delflge
     *
     * @return the value of students.delflge
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public Integer getDelflge() {
        return delflge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.delflge
     *
     * @param delflge the value for students.delflge
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public void setDelflge(Integer delflge) {
        this.delflge = delflge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.create_date
     *
     * @return the value of students.create_date
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.create_date
     *
     * @param createDate the value for students.create_date
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.update_date
     *
     * @return the value of students.update_date
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.update_date
     *
     * @param updateDate the value for students.update_date
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.delete_date
     *
     * @return the value of students.delete_date
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public Date getDeleteDate() {
        return deleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.delete_date
     *
     * @param deleteDate the value for students.delete_date
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }
}