package com.example.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

import com.example.demo.entity.Students;
import com.example.demo.entity.StudentsExample;
@Mapper
public interface StudentsMapper {
//注意不要加stu
	@Update("update students set delflge = 1,delete_date = #{deleteDate} where id = #{id}")
	void stuDel(Students stu);
	
	List<Students> mainSearch(Students students);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    long countByExample(StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    int deleteByExample(StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    int insert(Students row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    int insertSelective(Students row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    List<Students> selectByExample(StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    Students selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    int updateByExampleSelective(@Param("row") Students row, @Param("example") StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    int updateByExample(@Param("row") Students row, @Param("example") StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    int updateByPrimaryKeySelective(Students row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Tue May 27 21:52:46 JST 2025
     */
    int updateByPrimaryKey(Students row);
}